// 错误码定义
export const ERROR_CODES = {
  // 认证相关错误 (AUTH_*)
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_INSUFFICIENT_PERMISSIONS: "AUTH_INSUFFICIENT_PERMISSIONS",

  // 请求相关错误 (REQUEST_*)
  REQUEST_INVALID_PARAMS: "REQUEST_INVALID_PARAMS",
  REQUEST_MISSING_PARAMS: "REQUEST_MISSING_PARAMS",
  REQUEST_VALIDATION_FAILED: "REQUEST_VALIDATION_FAILED",
  REQUEST_RATE_LIMIT: "REQUEST_RATE_LIMIT",

  // 资源相关错误 (RESOURCE_*)
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS",
  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",

  // 服务相关错误 (SERVICE_*)
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  SERVICE_TIMEOUT: "SERVICE_TIMEOUT",
  SERVICE_DATABASE_ERROR: "SERVICE_DATABASE_ERROR",
  SERVICE_KV_ERROR: "SERVICE_KV_ERROR",

  // 通用错误 (GENERAL_*)
  GENERAL_INTERNAL_ERROR: "GENERAL_INTERNAL_ERROR",
  GENERAL_BAD_REQUEST: "GENERAL_BAD_REQUEST",
} as const;

// 错误消息映射
export const ERROR_MESSAGES: Record<string, string> = {
  [ERROR_CODES.AUTH_REQUIRED]: "需要登录才能访问此资源",
  [ERROR_CODES.AUTH_INVALID_TOKEN]: "无效的认证令牌",
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: "认证令牌已过期",
  [ERROR_CODES.AUTH_INSUFFICIENT_PERMISSIONS]: "权限不足",

  [ERROR_CODES.REQUEST_INVALID_PARAMS]: "请求参数无效",
  [ERROR_CODES.REQUEST_MISSING_PARAMS]: "缺少必需的请求参数",
  [ERROR_CODES.REQUEST_VALIDATION_FAILED]: "请求数据验证失败",
  [ERROR_CODES.REQUEST_RATE_LIMIT]: "请求频率超限，请稍后再试",

  [ERROR_CODES.RESOURCE_NOT_FOUND]: "请求的资源不存在",
  [ERROR_CODES.RESOURCE_ALREADY_EXISTS]: "资源已存在",
  [ERROR_CODES.RESOURCE_CONFLICT]: "资源冲突",

  [ERROR_CODES.SERVICE_UNAVAILABLE]: "服务暂时不可用",
  [ERROR_CODES.SERVICE_TIMEOUT]: "服务响应超时",
  [ERROR_CODES.SERVICE_DATABASE_ERROR]: "数据库操作失败",
  [ERROR_CODES.SERVICE_KV_ERROR]: "KV存储操作失败",

  [ERROR_CODES.GENERAL_INTERNAL_ERROR]: "服务器内部错误",
  [ERROR_CODES.GENERAL_BAD_REQUEST]: "请求格式错误",
};

// HTTP状态码映射
export const ERROR_STATUS_CODES: Record<string, number> = {
  [ERROR_CODES.AUTH_REQUIRED]: 401,
  [ERROR_CODES.AUTH_INVALID_TOKEN]: 401,
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: 401,
  [ERROR_CODES.AUTH_INSUFFICIENT_PERMISSIONS]: 403,

  [ERROR_CODES.REQUEST_INVALID_PARAMS]: 400,
  [ERROR_CODES.REQUEST_MISSING_PARAMS]: 400,
  [ERROR_CODES.REQUEST_VALIDATION_FAILED]: 422,
  [ERROR_CODES.REQUEST_RATE_LIMIT]: 429,

  [ERROR_CODES.RESOURCE_NOT_FOUND]: 404,
  [ERROR_CODES.RESOURCE_ALREADY_EXISTS]: 409,
  [ERROR_CODES.RESOURCE_CONFLICT]: 409,

  [ERROR_CODES.SERVICE_UNAVAILABLE]: 503,
  [ERROR_CODES.SERVICE_TIMEOUT]: 504,
  [ERROR_CODES.SERVICE_DATABASE_ERROR]: 500,
  [ERROR_CODES.SERVICE_KV_ERROR]: 500,

  [ERROR_CODES.GENERAL_INTERNAL_ERROR]: 500,
  [ERROR_CODES.GENERAL_BAD_REQUEST]: 400,
};
